PRAGMA foreign_keys = ON;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS rents;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS book_category;

CREATE TABLE IF NOT EXISTS books (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  author TEXT NOT NULL,
  description TEXT,
  total INTEGER NOT NULL DEFAULT 0,
  amount INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS rents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  book_id INTEGER NOT NULL,
  rent_date DATETIME  DEFAULT NULL,
  return_date DATETIME  DEFAULT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (book_id) REFERENCES books(id)
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(50) NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  age INTEGER NOT NULL,
  role_id INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS categories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS book_category (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  book_id INTEGER NOT NULL,
  category_id INTEGER NOT NULL,
  FOREIGN KEY (book_id) REFERENCES books(id),
  FOREIGN KEY (category_id) REFERENCES categories(id)
);

INSERT INTO users VALUES (1, 'admin', 'admin@admin.com', '$2a$10$RV3xeeBiXU0hvseJKAv58OjKwFUgU1VdDRSIboMeGSs0W.5HvAy8W',22,1); -- password:1
INSERT INTO users VALUES (2, 'user', 'user@admin.com', '$2a$10$RV3xeeBiXU0hvseJKAv58OjKwFUgU1VdDRSIboMeGSs0W.5HvAy8W',22,2); -- password:1
